#!/usr/bin/env python

import os
from Groove import *

myGroove = Groove("D")
#myGroove.key = "G"

myGroove.genMelody()

myGroove.printGroove()

# Create bash script to play tune
noteString = ""
currList = []
for phrase in myGroove.melody.phraseList:
    for note in phrase.noteList:
        keyOffset = 0
        if myGroove.key == "C":
            keyOffset = 0
        if myGroove.key == "D":
            keyOffset = 1
        if myGroove.key == "E":
            keyOffset = 2
        if myGroove.key == "F":
            keyOffset = 3
        if myGroove.key == "G":
            keyOffset = 4
        if myGroove.key == "A":
            keyOffset = 5
        if myGroove.key == "B":
            keyOffset = 6
        currList.append(keyOffset + note.octave*12+note.noteVal+Groove.scaleSteps[note.noteVal])
        print "Adding: " + str(keyOffset + note.octave*12+Groove.scaleSteps[note.noteVal])
        #noteString += str(note.octave)
        #noteString += ","
for i in range(len(currList)):
    noteString += str(myGroove.allNotesFreqsDict[myGroove.allNotesList[currList[i]]])
    noteString += ","
noteString = noteString[:len(noteString)-1] # remove final comma
dirPath = os.path.dirname(os.path.realpath(__file__))
resultsFile = dirPath + "/results.sh"

file1 = open(resultsFile, 'w')
file1.write("#!/bin/bash\nfor i in {" + noteString + "};do play -qn synth 2 pluck $i& sleep .25; done")


#print "noteString: " + noteString


